# script to load all necessary libraries
# pkgTest will load package if already installed, or install and load package if not already installed.
# added by HW 02.21.20


pkgTest <- function(x){
  if (!require(x,character.only = TRUE))
  {
    install.packages(x,dep=TRUE)
    if(!require(x,character.only = TRUE)) stop("Package not found")
  }
}

# pkgTest("SDMTools")
pkgTest("ncdf4")
# pkgTest("RCurl")
pkgTest("raster")
pkgTest("data.table")
# pkgTest("lunar")
pkgTest("R.utils")
pkgTest("RColorBrewer")
pkgTest("gbm")
pkgTest("colorRamps")
pkgTest("maps")
pkgTest("mapdata")
pkgTest("tweedie")
pkgTest("mgcv")
pkgTest("gamm4")
pkgTest("sp")
pkgTest("rgdal")
pkgTest("fields")
pkgTest("maptools")
# pkgTest("adehabitatHR")
# pkgTest("adehabitatHS")
# pkgTest("adehabitatLT")
# pkgTest("adehabitatMA")
pkgTest("tidyverse")
pkgTest("magrittr")
pkgTest("dismo")
pkgTest("caret")
pkgTest("mlbench")
pkgTest("cowplot")
pkgTest("gdata")
# pkgTest("plotly")
# pkgTest("tiff")
pkgTest("MASS")
pkgTest("ggmap")
# pkgTest("d3heatmap")
pkgTest("rasterVis")
pkgTest("corrplot")
# pkgTest("factoextra")
pkgTest("gplots")
# pkgTest("sf")
# pkgTest("rnaturalearth")
# pkgTest("rnaturalearthdata")
# pkgTest("rmapshaper")
pkgTest("glue")
pkgTest("parallel")
pkgTest("fasterize")
pkgTest("lubridate")
pkgTest("rgeos")
pkgTest("mgcv")
pkgTest("lme4")
# pkgTest("MuMIn")
# pkgTest("ggExtra")
to360 <- function(x) {x %% 360}